# Generated by Django 4.1.3 on 2022-11-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=5, null=True)),
                ('image', models.FileField(null=True, upload_to='defaultcatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('icon', models.FileField(null=True, upload_to='catagory')),
                ('restaurent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.restaurant')),
            ],
        ),
    ]
