# Generated by Django 4.1.3 on 2022-11-21 04:32

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("website", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("cart_id", models.CharField(max_length=200, null=True))],
        ),
        migrations.CreateModel(
            name="CartItems",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.IntegerField(default=0, null=True)),
                ("cart", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="website.cart")),
                ("product", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="website.product")),
            ],
        ),
    ]
