# Generated by Django 4.1.3 on 2022-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_defaultcats_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultcats',
            name='no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
