# Generated by Django 4.1.3 on 2022-11-21 07:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("website", "0004_cartitems_total")]

    operations = [migrations.AlterField(model_name="cartitems", name="total", field=models.FloatField(blank=True, null=True))]
