# Generated by Django 4.1.3 on 2022-11-23 06:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("website", "0005_alter_cartitems_total")]

    operations = [
        migrations.CreateModel(
            name="FrontBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(blank=True, null=True, upload_to="front-banner")),
            ],
        ),
        migrations.CreateModel(
            name="ProductPageBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(blank=True, null=True, upload_to="Product-banner")),
            ],
        ),
    ]
