# Generated by Django 4.1.3 on 2022-11-26 04:38

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("website", "0009_restobanner")]

    operations = [
        migrations.AddField(
            model_name="restobanner", name="resto", field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="website.restaurant")
        )
    ]
