# Generated by Django 4.1.3 on 2022-11-29 06:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("website", "0010_restobanner_resto")]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("video", models.FileField(blank=True, null=True, upload_to="video")),
            ],
            options={"verbose_name_plural": "Video"},
        )
    ]
